name: Reusable Testing

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      test-matrix:
        type: string
        required: true


defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.test-matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          torch-version: ${{ matrix.torch-version }}
          cuda-version: ${{ matrix.cuda-version }}

      - name: Install graphviz
        if: ${{ runner.os == 'Linux' && matrix.full_test == '1' }}
        run: |
          sudo apt-get install graphviz

      - name: Install main package (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          uv pip install -e ".[test]"

      - name: Install main package
        if: ${{ runner.os != 'Windows' }}
        run: |
          uv pip install -e ".[full,test]"

      - name: Check installation
        run: |
          python -c "import torch; print('PyTorch:', torch.__version__)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
          python -c "import torch; print('CUDA:', torch.version.cuda)"
        shell: bash

      - name: Run tests
        timeout-minutes: 20
        run: |
          pytest --cov --cov-report=xml --durations 10
        env:
          FULL_TEST: ${{ matrix.full_test }}

      - name: Upload coverage
        if: ${{ runner.os == 'Linux' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
