name: Testing previous PyTorch

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - 'torch_geometric/**'
      - 'test/**'
      - 'pyproject.toml'
      - '.github/actions/setup/action.yml'
      - '.github/workflows/testing_prev.yml'
  pull_request:
    paths:
      - 'torch_geometric/**'
      - 'test/**'
      - 'pyproject.toml'
      - '.github/actions/setup/action.yml'
      - '.github/workflows/testing_prev.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  prev_pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        torch-version: [2.6.0, 2.7.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          torch-version: ${{ matrix.torch-version }}

      - name: Install main package
        run: |
          uv pip install -e ".[test]"

      - name: Check installation
        run: |
          python -c "import torch; print('PyTorch:', torch.__version__)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
          python -c "import torch; print('CUDA:', torch.version.cuda)"
        shell: bash

      - name: Run tests
        timeout-minutes: 15
        run: |
          pytest --durations 10
