name: Testing latest PyTorch

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - 'torch_geometric/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'codecov.yml'
      - '.github/actions/setup/action.yml'
      - '.github/workflows/testing_latest.yml'
  pull_request:
    paths:
      - 'torch_geometric/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'codecov.yml'
      - '.github/actions/setup/action.yml'
      - '.github/workflows/testing_latest.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install main package (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          uv pip install -e ".[test]"

      - name: Install main package
        if: ${{ runner.os != 'Windows' }}
        run: |
          uv pip install -e ".[full,test]"

      - name: Check installation
        run: |
          python -c "import torch; print('PyTorch:', torch.__version__)"
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
          python -c "import torch; print('CUDA:', torch.version.cuda)"
        shell: bash

      - name: Run tests
        timeout-minutes: 15
        run: |
          pytest --cov --cov-report=xml --durations 10

      - name: Upload coverage
        if: ${{ runner.os == 'Linux' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
