name: Testing latest PyTorch

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - 'torch_geometric/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'codecov.yml'
      - '.github/actions/setup/action.yml'
      - '.github/workflows/testing_latest.yml'
  pull_request:
    paths:
      - 'torch_geometric/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'codecov.yml'
      - '.github/actions/setup/action.yml'
      - '.github/workflows/testing_latest.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  latest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    uses: ./.github/workflows/_testing.yml
    with:
      test-matrix: |
        {
          os: ["ubuntu-22.04", "macos-14", "windows-2022"],
          python-version: ["3.10"],
          torch-version: ["2.8.0"],
          cuda-version: ["cpu"]
        }

  nightly:
    if: github.repository == 'pyg-team/pytorch_geometric'
    uses: ./.github/workflows/_testing.yml
    with:
      test-matrix: |
        {
          os: ["ubuntu-22.04"],
          python-version: ["3.10"],
          torch-version: ["nightly"],
          cuda-version: ["cpu"]
        }

  # gpu:
  #   if: github.repository == 'pyg-team/pytorch_geometric'
  #   uses: ./.github/workflows/_testing.yml
  #   with:
  #     test-matrix: |
  #       {
  #         "os": [["self-hosted, nvidia"]],
  #         "python-version": ["3.10"],
  #         "torch-version": ["2.8.0"],
  #         "cuda-version": ["cu128"]
  #       }
